In [1]:
## loads python modules to work with data
import pandas as pd
import numpy  as np
from pathlib import Path

In [3]:
## loads specific package modules, which contain project settings
from client_segmentation.config import PROCESSED_DATA_DIR
from client_segmentation.config import RAW_DATA_DIR
from client_segmentation.config import INTERIM_DATA_DIR

In [4]:
## lists the non hidden files at INTERIM directory
for curr_file in INTERIM_DATA_DIR.iterdir():
    if curr_file.name.startswith('.') == False:
        print(curr_file.name)

product_category_name_translation.csv
olist_sellers_dataset.csv
olist_geolocation_dataset.csv
olist_products_dataset.csv
olist_order_items_dataset.csv
olist_order_payments_dataset.csv
olist_orders_dataset.csv
olist_order_reviews_dataset.csv
olist_customers_dataset.csv

## Analysis of product_category_name_translation.csv

In [5]:
dataset = pd.read_csv( INTERIM_DATA_DIR / 'product_category_name_translation.csv' )

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB

In [8]:
dataset.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [14]:
dataset.isna().sum()

product_category_name            0
product_category_name_english    0
dtype: int64

In [16]:
dataset.duplicated().sum()

0

The file 'product_category_name_translation.csv' contains unique names
for product category in brazilian portuguese and their respective
translation in english. No null or duplicated values were found.

### Data dictionary
| Column | Type | Description |
| :--- | :--- | :--- |
| product_category_name | string | name of a product category in portugese |
| product_category_name_english | string | name of a product category in  english |

## Analysis of olist_sellers_dataset.csv

In [17]:
dataset = pd.read_csv( INTERIM_DATA_DIR / 'olist_sellers_dataset.csv' )

In [18]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB

In [19]:
dataset.head(5)

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [20]:
dataset.isna().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [21]:
dataset.duplicated().sum()

0

In [24]:
dataset['seller_state'].value_counts()

seller_state
SP    1849
PR     349
MG     244
SC     190
RJ     171
RS     129
GO      40
DF      30
ES      23
BA      19
CE      13
PE       9
PB       6
RN       5
MS       5
MT       4
RO       2
SE       2
PI       1
AC       1
MA       1
AM       1
PA       1
Name: count, dtype: int64

In [23]:
dataset.loc[:, ['seller_city', 'seller_state']].value_counts()

seller_city     seller_state
sao paulo       SP              694
curitiba        PR              124
rio de janeiro  RJ               93
belo horizonte  MG               66
ribeirao preto  SP               52
                               ...
itau de minas   MG                1
itapui          SP                1
itaporanga      SP                1
itapeva         SP                1
xaxim           SC                1
Name: count, Length: 636, dtype: int64

### Data dictionary
| Column | Type | Description |
| :--- | :--- | :--- |
| seller | object | an id from a seller (for example 3442f8959a84dea7ee197c632cb2df15) |
| seller_zip_code_prefix | int64 | a number which identifies a zip code |
| seller city | string | the city from the seller |
| seller_state | string | the state from the seller |